from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class codeTable(db.Model):
    ### This table contains the code generated by a teacher. 
    __tablename__ = "codeTable"
    id = db.Column(db.Integer, primary_key = True)
    code = db.Column(db.String)

    def __init__(self,code):
        self.code = code
